### PR TITLE
jakartaee8

### PR DESCRIPTION
**Pull request by hantsy**

### CODE REVIEW

**Comment by m-reza-rahman** [comment]
There is another issue I just noticed. Could you please put back the XML configuration? The reason the configuration is in XML is that it allows us to do variable substitution in Maven (http://ovaraksin.blogspot.com/2011/09/filter-webxml-with-maven.html). This has proven to be very important while creating application server specific builds and quite possibly during cloud deployment.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by hantsy** [comment]
@m-reza-rahman Thanks for your suggestions.  

In fact, Payara and WildFly support **environment variables introspecting** in the `@DataSourceDefinition` annotation attributes, this is more ideal when switching to varied environments, but after I checked some docs, they used different formats, personally, I hope this should be considered in the upcoming Jakarta EE 10 (Config spec), allow annotation attributes to be configured as EL string as united formats, such as **`${evn.JDBC_DATASOURCE_URL:http://localhost:5432}`**, **`${evn['JDBC_DATASOURCE_URL']:http://localhost:5432}`** to read from system env variables.  

Now I am focusing on the testing codes and WildFly integrations, there are still some problems there. I will restore the Web.xml filter and handle this later. Thanks again.

**Comment by m-reza-rahman** [comment]
Please do focus a bit on getting a PR merged if possible? That way, all of us can focus on moving forward the Jakarta EE 8 work? Also, it is in general difficult to merge very large PRs because of the Eclipse Foundation IP checks. Changes of less than 1,000 lines are highly preferred.

I think expanding application server support can wait a bit more. It is a more non-trivial exercise than it may appear, especially in the persistence tier.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by hantsy** [comment]
> Please do focus a bit on getting a PR merged if possible? That way, all of us can focus on moving forward the Jakarta EE 8 work? Also, it is in general difficult to merge very large PRs because of the Eclipse Foundation IP checks. Changes of less than 1,000 lines are highly preferred.

I will try to rebase some commits into meaningful commit logs and split this pr into multi prs if it is required in future. I will add more tests about the Repositories. 

> I think expanding application server support can wait a bit more. It is a more non-trivial exercise than it may appear, especially in the persistence tier.

About the WildFly integration, it is for my personal reason. Payara related artifacts used a private Github maven repo internally, it is disconnected frequently from my local system(esp. in China, if you live out of China, I think this is not a problem), and it also can NOT be worked using my local proxy or adding this repo URL in my pom.xml. I remember I reported the issues on the Payara project, but no response to this.

**Pull request merged**
